# Generated by Django 5.1.2 on 2024-10-29 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_trip_start_location_lat_trip_start_location_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='start_location_lat',
            field=models.FloatField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_location_long',
            field=models.FloatField(blank=True, max_length=255),
        ),
    ]
